import Head from "next/head";
import { Inter } from "next/font/google";
import Message from "@/components/Message";
import { Container } from "@mui/system";
import InitSection from "@/components/InitSection";
import Services from "./ServiceSection";
import { getDevice } from "@/utils/commonUtils";
const inter = Inter({ subsets: ["latin"] });

const messageData = [
  {
    name: "Gursimran Singh",
    image: "guriImage.jpeg",
    message:
      "this is some dummy message about the company this is some dummy message about the company this is some dummy message about the company",
    align: "left",
    position: "abc @ PNG Software Technologies",
  },
  {
    name: "Parth Aggarwal",
    image: "guriImage.jpeg",
    message:
      "this is some dummy message about the company this is some dummy message about the company this is some dummy message about the company",
    align: "right",
    position: "abc @ PNG Software Technologies",
  },
];
export default function Home({ device }: any) {
  if (device === "mobile") {
    return (
      <div style={{ textAlign: "center", marginTop: "40%", color: 'white', fontSize: '3rem' }}>
        Mobile site coming soon... view on desktop version
      </div>
    );
  }
  return (
    <div style={{ color: "white" }}>
      <Head>
        <title>PNG software Technologies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InitSection />
      <Container maxWidth="lg">
        {messageData.map((data: any) => {
          return <Message key={data.name} data={data} />;
        })}
      </Container>
      <div id="services" style={{ paddingTop: "30px" }}>
        <h1>Services We Offer:</h1>
        <Services />
      </div>
    </div>
  );
}

export function getServerSideProps(context: any) {
  const device = getDevice(context.req.headers["user-agent"]);
  return {
    props: {
      device,
    },
  };
}
