import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Message from "@/components/Message";
import { color, Container, display, width } from "@mui/system";
import { Fab } from "@mui/material";
import ArrowDownwardIcon from "@mui/icons-material/ArrowDownward";
import InitSection from "@/components/InitSection";
import Services from "./ServiceSection";
const inter = Inter({ subsets: ["latin"] });

const messageData = [
  {
    name: "Gursimran Singh",
    image: "guriImage.jpeg",
    message:
      "this is some dummy message about the company this is some dummy message about the company this is some dummy message about the company",
    align: "left",
    position: "abc @ PNG Software Technologies",
  },
  {
    name: "Parth Aggarwal",
    image: "guriImage.jpeg",
    message:
      "this is some dummy message about the company this is some dummy message about the company this is some dummy message about the company",
    align: "right",
    position: "abc @ PNG Software Technologies",
  },
];
export default function Home() {
  return (
    <div style={{ color: "white" }}>
      <Head>
        <title>PNG software Technologies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InitSection />
      <Container maxWidth="lg">
        {messageData.map((data: any) => {
          return <Message key={data.name} data={data} />;
        })}
      </Container>
      <div id="services" style={{ paddingTop: "30px" }}>
        <h1>Services We Offer:</h1>
        <Services />
      </div>
    </div>
  );
}
